language: android

jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a

# Turn off caching to avoid any caching problems
cache: false

# Use the Travis Container-Based Infrastructure
sudo: require
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}


before_install:
  - chmod +x gradlew

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always



